import {
  Blogging,
  CompanyLogo1,
  CompanyLogo2,
  CompanyLogo3,
  CompanyLogo4,
  Coursera,
  DiamondLgBlue,
  DiamondLgGreen,
  DiamondLgOrange,
  DiamondLgPink,
  DiamondLgYellow,
  Gaming,
  Google,
  Linkedin,
  Reading,
  SkillCss,
  SkillFigma,
  SkillHtml5,
  SkillPhotoshop,
  SkillSketch,
  SkillTrello,
  SkillWireframe,
  SkillXd,
  Travelling,
  Udemy,
} from "../assets/image";

const DATA = {
  professionalExperiences: [

  ],
  educationalExperiences: [
    {
      id: "edu_d1",
      icon: DiamondLgYellow,
      course: "Computing Science",
      institution: "Simon Fraser University",
      degree: "Bachelor of Science",
      startDate: "2021",
      endDate: "",
    },
    {
      id: "edu_1",
      icon: DiamondLgBlue,
      course: "Embedded Systems",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Spring 2024",
      endDate: "",
    },
    {
      id: "edu_2",
      icon: DiamondLgGreen,
      course: "Special Topics in Artificial Intelligence",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Spring 2024",
      endDate: "",
    },
    {
      id: "edu_3",
      icon: DiamondLgOrange,
      course: "Computational Data Science",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Fall 2023",
      endDate: "",
    },
    {
      id: "edu_4",
      icon: DiamondLgPink,
      course: "Programming Languages",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Summer 2023",
      endDate: "",
    },
    {
      id: "edu_5",
      icon: DiamondLgYellow,
      course: "Networking I",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Summer 2023",
      endDate: "",
    },
    {
      id: "edu_6",
      icon: DiamondLgBlue,
      course: "Data Structures & Algorithms",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Summer 2023",
      endDate: "",
    },
    {
      id: "edu_7",
      icon: DiamondLgGreen,
      course: "Operating Systems",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Spring 2023",
      endDate: "",
    },
    {
      id: "edu_8",
      icon: DiamondLgOrange,
      course: "Numerical Analysis I",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Fall 2022",
      endDate: "",
    },
    {
      id: "edu_9",
      icon: DiamondLgPink,
      course: "Computational Linguistics",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Fall 2022",
      endDate: "",
    },
    {
      id: "edu_10",
      icon: DiamondLgYellow,
      course: "Intoduction to Artificial Intelligence",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Fall 2022",
      endDate: "",
    },
    {
      id: "edu_11",
      icon: DiamondLgBlue,
      course: "Database Systems I",
      institution: "Simon Fraser University",
      degree: "Upper Division Course",
      startDate: "Summer 2022",
      endDate: "",
    },
    {
      id: "edu_d2",
      icon: DiamondLgGreen,
      course: "Applied Linguistics",
      institution: "University of Saskatchewan",
      degree: "Bachelor of Arts",
      startDate: "2013",
      endDate: "2019",
    },
    {
      id: "edu_d3",
      icon: DiamondLgOrange,
      course: "French",
      institution: "University of Saskatchewan",
      degree: "Bachelor of Arts",
      startDate: "2013",
      endDate: "2019",
    },
  ],
  skills: [

  ],
  certificatesAndAwards: [
    {
      id: "cert_award_1",
      icon: Linkedin,
      provider: "LinkedIn",
      course: "DevOps Institute Cert Prep: SRE Foundation (SRE)",
      startDate: "July 2024",
      endDate: "July 2024",
    },
  ],
  hobbiesAndInterests: [

  ],
};

export default DATA;
